name: Update workshop packages
on:
  push:
    branches:
      - main
      - feat/add_terraform

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform
      run:  cd terraform && zip -r ../terraform.zip .

    - name: .NET zip solutions
      run:  cd src/solutions/dotnet && zip -r ../../../dotnet-solution.zip .

    - name: NodeJS zip solutions
      run:  cd src/solutions/nodejs && zip -r ../../../nodejs-solution.zip .

    - name: python zip solutions
      run:  cd src/solutions/python && zip -r ../../../python-solutions.zip .

    - name: zip webapp
      run:  cd src/webapp && zip -r ../../webapp.zip .

    - name: Update release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Workshop packages
        tag: latest
        artifacts: "*.zip"
        allowUpdates: true